package com.clipshare.crypto

import java.security.MessageDigest
import javax.crypto.Cipher
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.SecretKeySpec

object E2ECrypto {
    private const val GCM_NONCE_LENGTH = 12
    private const val GCM_TAG_BITS = 128
    private val AAD = "greenpaste-v1".toByteArray(Charsets.UTF_8)

    fun deriveKey(tokenHex: String): SecretKey {
        val tokenBytes = hexToBytes(tokenHex)
        val hash = MessageDigest.getInstance("SHA-256").digest(tokenBytes)
        return SecretKeySpec(hash, "AES")
    }

    fun deviceTag(tokenHex: String): ByteArray {
        val tokenBytes = hexToBytes(tokenHex)
        val hash = MessageDigest.getInstance("SHA-256").digest(tokenBytes)
        return hash.copyOfRange(0, 8)
    }

    fun seal(plaintext: ByteArray, key: SecretKey): ByteArray {
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.ENCRYPT_MODE, key)
        cipher.updateAAD(AAD)
        val ciphertext = cipher.doFinal(plaintext)
        // cipher.iv is the 12-byte nonce generated by the provider
        // ciphertext includes the 16-byte auth tag appended by GCM
        return cipher.iv + ciphertext
    }

    fun open(blob: ByteArray, key: SecretKey): ByteArray {
        require(blob.size > GCM_NONCE_LENGTH + GCM_TAG_BITS / 8) { "Blob too short" }
        val nonce = blob.copyOfRange(0, GCM_NONCE_LENGTH)
        val ciphertextWithTag = blob.copyOfRange(GCM_NONCE_LENGTH, blob.size)
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(GCM_TAG_BITS, nonce))
        cipher.updateAAD(AAD)
        return cipher.doFinal(ciphertextWithTag)
    }

    private fun hexToBytes(hex: String): ByteArray {
        val len = hex.length
        val data = ByteArray(len / 2)
        for (i in 0 until len step 2) {
            data[i / 2] = ((Character.digit(hex[i], 16) shl 4) + Character.digit(hex[i + 1], 16)).toByte()
        }
        return data
    }
}
